export const GROUPS = {
  perso: new Set([
    "Prenom",
    "Nom_de_famille",
    "Date_de_naissance",
    "Age",
    "Genre",
    "Nationalite",
    "Majeur",
    "AIE",
    "Niveau_de_langue",
    "Niveau_etudes_reconnu_en_France",
    "PMR",
    "RQTH",
  ]),
  coord: new Set([
    "Adresse",
    "Email",
    "Tel",
    "Departement_domicile_inscription",
  ]),
  admin: new Set([
    "Regularite_situation",
    "Date_validite_titre_sejour",
    "Numero_unique_enregistrement",
    "Attestation_MSA_CAF",
    "Document_identite_sejour_candidats",
    "Document_identite_sejour_autres_personnes",
  ]),
  besoins: new Set([
    "Precarite_de_logement",
    "Situation_hebergement",
    "Situation_financiere",
    "Situation_face_emploi",
    "Besoin_divers",
    "Difficultes_diverses",
    "Besoin_mise_a_l_abri",
    "Besoin_prise_en_charge_enfant_s_",
    "Besoin_accompagner_conjoint_e_vers_emploi_formation",
  ]),
  complements: new Set([
    "Motivation_candidat",
    "Autres_initiatives_perso",
    "Complement_info_Emploi_Formation",
    "Complement_info_Finances",
    "Complement_info_Mobilite",
    "Vehicule",
    "Permis",
    "Commentaire_du_statut",
  ]),
} as const;

export const GROUP_TITLES: Record<keyof typeof GROUPS, string> = {
  perso: "Informations personnelles",
  coord: "Coordonnées",
  admin: "Administratif",
  besoins: "Besoins",
  complements: "Compléments",
};